name: Trigger GitHub Actions from External Source

on:
  workflow_dispatch:

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger another workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.TEST }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"ref":"main"}' \
            "https://api.github.com/repos/your_username/your_repo/actions/workflows/your_workflow.yml/dispatches"
