name: Run PDF Script

on:
  workflow_dispatch: # Umožní ruční spuštění workflow z GitHubu

jobs:
  run-pdf-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: List files before running script
        run: ls -l  # Ukáže obsah adresáře před spuštěním skriptu

      - name: Run script
        run: node script.js

      - name: List files after running script
        run: ls -l  # Ukáže obsah adresáře po spuštění skriptu

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-pdf  # Jméno artefaktu
          path: ./output.pdf  # Cesta k souboru
